# Generated by Django 3.2.13 on 2022-12-05 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catarticle',
            name='breed',
        ),
        migrations.RemoveField(
            model_name='dogarticle',
            name='breed',
        ),
        migrations.AddField(
            model_name='dogarticle',
            name='dog_breed',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='articles.dogcategory'),
            preserve_default=False,
        ),
    ]
