# Generated by Django 3.2.13 on 2022-11-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20221129_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catarticlecomment',
            old_name='article',
            new_name='catarticle',
        ),
        migrations.RenameField(
            model_name='dogarticlecomment',
            old_name='article',
            new_name='dogarticle',
        ),
    ]
