# Generated by Django 3.2.13 on 2022-11-30 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20221129_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catarticle',
            name='breed',
            field=models.CharField(choices=[('페르시안', '페르시안'), ('러시안블루', '러시안블루'), ('샴', '샴'), ('렉돌', '렉돌'), ('스코티쉬폴드', '스코티쉬폴드')], max_length=20),
        ),
        migrations.AlterField(
            model_name='catarticle',
            name='gender',
            field=models.CharField(choices=[('암컷', '암컷'), ('수컷', '수컷')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dogarticle',
            name='breed',
            field=models.CharField(choices=[('포메라니안', '포메라니안'), ('웰시코기', '웰시코기'), ('말티즈', '말티즈'), ('시츄', '시츄'), ('푸들', '푸들'), ('비숑', '비숑'), ('시바견', '시바견'), ('골든 리트리버', '골든 리트리버')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dogarticle',
            name='gender',
            field=models.CharField(choices=[('암컷', '암컷'), ('수컷', '수컷')], max_length=20),
        ),
    ]
