# Generated by Django 3.2.13 on 2022-11-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20221130_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catarticle',
            name='neutered',
            field=models.CharField(choices=[('Yes', 'Yes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='catarticle',
            name='vaccination',
            field=models.CharField(choices=[('Yes', 'Yes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dogarticle',
            name='neutered',
            field=models.CharField(choices=[('Yes', 'Yes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dogarticle',
            name='vaccination',
            field=models.CharField(choices=[('Yes', 'Yes')], max_length=20),
        ),
    ]
