# Generated by Django 3.2.13 on 2022-11-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20221130_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catarticle',
            name='neutered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='catarticle',
            name='vaccination',
            field=models.BooleanField(default=False),
        ),
    ]
