# Generated by Django 3.2.13 on 2022-11-29 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='volunteer_c',
            field=models.CharField(choices=[('YES', '지원'), ('NO', '미지원')], max_length=3, null=True),
        ),
    ]
